### ISSUE TITLE
[Hacktoberfest] make the glow effect configurable

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/synthwave84.nvim#4]
the glow effect should be configurable

**Comment by acass91** [comment]
Hi @ChristianChiarulli , I have a draft that makes this configurable. https://github.com/LunarVim/synthwave84.nvim/pull/5

Example with func and operator set to non-defaults:

```
cat ~/.config/nvim/lua/user/synthwave84.lua 

require("synthwave84").setup({
  glow = {
    error_msg = true,
    type2 = true,
    func = false,
    keyword = true,
    operator = true
  }
})
```
Side note - Without any changes, the highlighting for NightDrive.js looks different for me than it does in the screenshot. I don't have an active LSP for JavaScript if that makes a difference.

![image](https://user-images.githubusercontent.com/6621993/193987665-beac9a81-8a4a-4e4a-86a8-6d8ca8ffa2ab.png)

**Comment by acass91** [comment]
Hi @ChristianChiarulli can you please check out my pull request?

**Comment by ChristianChiarulli** [comment]
my b, merged

**Comment by acass91** [comment]
Thanks :)
